#index:
#    path: /
#    controller: App\Controller\DefaultController::index

products_list:
    path: /products
    controller: App\Controller\ProductController::class
    defaults:
      route: 'product_inventory'
      permanent: true

      keepQueryParams: true

      keepRequestMethod: true
